### ISSUE TITLE
Title: Issue: Implement Feature to Hide Navbar on Dashboard after Login

### ISSUE THREAD

**Issue by ARYANPATILSOLOCODER11** [ARYANPATILSOLOCODER11/CryptGuard#1]
Problem:
Upon logging into the website, the navbar remains visible on the dashboard, affecting user experience negatively.

Solution:
Integrate functionality to automatically hide the navbar upon reaching the dashboard after successful login.

Steps:

Update routing to direct to the dashboard post-login.
Implement logic in the layout component to conditionally hide the navbar on the dashboard.
Validate changes to ensure seamless navigation and consistent user interface behavior.
Expected Outcome:
<img width="791" alt="image" src="https://github.com/ARYANPATILSOLOCODER11/CryptGuard/assets/125760276/cfed4f1c-d779-4534-8a1f-59309e69dfc3">

Current Problem :-
<img width="924" alt="image" src="https://github.com/ARYANPATILSOLOCODER11/CryptGuard/assets/125760276/e7051689-2416-4473-be5f-1bf4f56daaa7">

The navbar should be concealed on the dashboard page after login, enhancing visual clarity and user focus.
Technologies: React, React Router

**Comment by NikhilPatil15** [comment]
Add a Boolean in initial state of authslice and then select it with useSelector() and do the conditional rendering if yes then show navbar no then don't:)

**Comment by ARYANPATILSOLOCODER11** [comment]
> We can store login and logout in store and use 'useDispatch()' and 'useState()' to ask the store is user login or not. As we can verify is user is login or not we can render element on that bases.
---
Solve it 
Problem Issued :- Shree
